apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-backend-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/python-backend-k8s-manifests.git
    targetRevision: HEAD
    path: k8s/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: python-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
